name: Docker CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build -t my-app:ci .

      - name: Start containers
        run: docker compose up -d --build